### ISSUE TITLE
npm list should specific package name

### ISSUE THREAD

**Issue by chilijung** [Canner/npm-check-install#3]
https://github.com/Canner/npm-check-install/blob/master/src/checkPkg.js#L8

Now we are listing all package name and find a specific package, which is causing unnecessary memory caching and performance issue, it can be simply done by `npm ls --json --parseable --depth=0 antd`
```
 lijungchi@Lide-MacBook-Air  ~/Documents/canner-platform/packages/cli   master ●  npm ls --json --parseable --depth=0 antd
{
  "name": "@canner/cli",
  "version": "2.5.2",
  "dependencies": {
    "antd": {
      "version": "3.10.0",
      "from": "antd@^3.10.0",
      "resolved": "https://registry.npmjs.org/antd/-/antd-3.10.0.tgz"
    }
  }
}
```

**Comment by chihsuan** [comment]
Merged. Close.
